baseURL = "https://cherry-vm-studio.github.io/cherry-vm-studio/"
title = "Cherry VM Studio Docs"
theme = "hugo-book"
languageCode = 'en-us'

publishDir = "public"

[params]
    BookTheme = "light"
    BookSection = "*"
    BookFavicon = "Cherry VM Studio Logo Small.png"
